resolver: lts-5.16

packages:
- '.'
- location: '../tangles'
  extra-dep: true
- location: '../diagrams-tangles'
  extra-dep: true

extra-deps:
- HaskellForMaths-0.4.8
- disjoint-set-0.2

flags:
  tangles:
    internal-tests: true

extra-package-dbs: []
